name: Continuous Deployment Workflow

# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches:
      - 'main'
    paths:
      - './'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    # Define the working directory for all run steps in the workflow
    working-directory: ./

jobs:

  deploy_staging:
    # environment: staging
    name: 'Deploy to staging'
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
        name: 'Checkout repository'

      - uses: wshihadeh/docker-deployment-action@master
        name: Start Deployment        
        with:
          remote_docker_host: ${{ secrets.REMOTE_HOSTNAME }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          deploy_path: /root/asusdin87/deploy/demo-dev/
          copy_stack_file: true
          stack_file_name: docker-compose.yml
          pull_images_first: false
          keep_files: 3
          args: -p demodev up -d