name: Continuous Deployment Workflow

# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches:
      - 'main'
    paths:
      - './'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    # Define the working directory for all run steps in the workflow
    working-directory: ./

jobs:

  deploy_staging:
    # environment: staging
    name: 'Deploy to staging'
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
        name: 'Checkout repository'

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOSTNAME }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_SSH_PRIVATE_KEY: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          NAME: "Root"

        with:
          hosts: '$REMOTE_USER@$REMOTE_HOST'
          privateKey: $REMOTE_SSH_PRIVATE_KEY
          command: ls -lah /root/asusdin87/deploy/