name: Continuous Deployment Workflow

# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches:
      - 'main'
    paths:
      - './'
  # workflow_dispatch:

defaults:
  run:
    shell: bash
    # Define the working directory for all run steps in the workflow
    working-directory: ./

jobs:

  # ======================================================
  # Deploy the main branch to staging
  # 
  # It's important to test the main branch in staging
  # before going to production with it.
  # ======================================================
  deploy_staging:
    # environment: staging
    name: 'Deploy to staging'
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
        name: 'Checkout repository'