on: push
name: Deploy to Docker swarm
uses: wshihadeh/docker-deployment-action@v1
with:
  remote_docker_host: root@31.220.108.134
  ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
  ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
  deployment_mode: docker-swarm
  copy_stack_file: true
  deploy_path: /root/asusdin87/deploy/demo-dev
  stack_file_name: docker-compose.yaml
  keep_files: 5
  args: demodev
