name: CD Workflow
# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches:
      - 'main'
    paths:
      - './'
  workflow_dispatch:
defaults:
  run:
    shell: bash
    # Define the working directory for all run steps in the workflow
    working-directory: ./
jobs:
  deploy_staging:
    # environment: staging
    name: 'Deploy to Demo-Dev'
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
        name: 'Checkout repository'

      - uses: asusdin87/ssh2-to-remote-action@main
        name: Upload directory to SFTP server        
        with:
          host: ${{ secrets.REMOTE_HOSTNAME }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWD }}
          local_dir: './'
          remote_base_dir: '/root/asusdin87/deploy/demo-dev'
    

      - uses: appleboy/ssh-action@v1.1.0
        name: Executing remote ssh commands using password
        env:
          REMOTE_BASE_DIR: "/root/asusdin87/deploy/demo-dev"
        with:
          host: ${{ secrets.REMOTE_HOSTNAME }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            ls -lha
            docker-compose -f $REMOTE_BASE_DIR/docker-compose.yaml ps -a

      - uses: mxschmitt/action-tmate@v3
        name: Setup tmate session      
        if: ${{ failure() }}

