# This is a basic workflow to help you get started with Actions

name: Deploy to Docker Host

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    #~ runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v1
            with:
                remote_docker_host: root@uxusolutions.com
                ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
                ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
                deployment_mode: docker-compose
                copy_stack_file: true
                deploy_path: /root/asusdin87/deploy/demo-dev/
                stack_file_name: docker-compose.yaml
                keep_files: 5
                args: up -d
                docker_prune: 'false'
                pull_images_first: 'false'
