name: Continuous Deployment Workflow

# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches:
      - 'main'
    paths:
      - './'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    # Define the working directory for all run steps in the workflow
    working-directory: ./

jobs:

  deploy_staging:
    # environment: staging
    name: 'Deploy to staging'
    runs-on: ubuntu-latest

    steps:
      
      #- uses: actions/checkout@v4
      #  name: 'Checkout repository'

      - uses: actions/checkout@v3
      - name: 'Deploy to staging'
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          legacy_allow_rsa_hostkeys: "true"
          path: ./
          remote_path: /root/asusdin87/deploy/demo-dev/
          remote_host: ${{ secrets.REMOTE_HOSTNAME }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}